version: '3.4'

services:
  api:
    env_file:
      - ~/.lookaroond.env
    build:
      context: api/.
    restart:
      always
    volumes:
      - /root/.nuget:/root/.nuget
    logging:
      options:
        max-size: "5m"
        max-file: "10"

  proxy:
    build: proxy/
    volumes:
      - /root/data/caddy_data/:/data
      - /root/data/caddy_config/:/config
    restart:
      always
    build:
      context: ${lookaroond_proxy:-./proxy}
    ports:
      - 443:443
      - 80:80
    logging:
      options:
        max-size: "5m"
        max-file: "10"

  db:
    image: mongo:4.4
    restart:
      always
    volumes:
      -  /root/data/lookaroond:/data/db
    logging:
      options:
        max-size: "5m"
        max-file: "10"