name: api deploy
on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Deployment
      uses: sagebind/docker-swarm-deploy-action@v2
      with:
        remote_host: ${{ secrets.DOCKER_REMOTE_HOST }}
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        args: stack deploy --compose-file docker-compose.yaml lookaroond