name: api deploy
on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Deployment
      uses: wshihadeh/docker-deployment-action@v2
      with:
        remote_docker_host: ${{ secrets.DOCKER_REMOTE_HOST }}
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        deployment_mode: docker-swarm
        deploy_path: /root/lookaroond
        copy_stack_file: true
        keep_files: 5
        args: lookaroond